---
name: "populate_processing_api"
pack: "ductus"
description: "Trigger workflow to populate processing api"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "workspace/INBOX"

action:
    ref: "ductus.populate_processing_api"
    parameters:
        runfolder: "{{trigger.runfolder}}"
        runfolder_host: "{{trigger.host }}"
        #project_type: "klinik"
