---
name: "process_inbox_wp3_tc"
pack: "ductus"
description: "Rule that triggers processing of WP3 TC inbox on compute"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "TwistCancer/Workarea"

action:
    ref: "ductus.process_inbox_wp3_tc"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
