---
name: "process_inbox_wp3_te"
pack: "ductus"
description: "Rule that triggers processing of WP3 TE inbox on compute"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "wp3/nobackup/TWIST/INBOX"

action:
    ref: "ductus.process_inbox_wp3_te"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
