---
name: "process_workspace"
pack: "ductus"
description: "Rule that triggers move action, will move clincal wp1  data to the inbox folder"
enabled: false

trigger:
    type: "ductus.processing_api"

criteria:
    trigger.event:
      type: "equals"
      pattern: "analysis_waiting"

action:
    ref: "ductus.process_workspace"
    parameters:
        analysis_name: "{{trigger.analysis_name}}"
        #project_type: "klinik"
