---
name: "retrieve_result_wp3_tc"
pack: "ductus"
description: "Rule that triggers retriving of wp3 tc results from compute"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "wp3/nobackup/TwistCancer/OUTBOX/"

action:
    ref: "ductus.retrieve_result_wp3_tc"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
