---
name: "wp1_research_preprocess_inbox"
pack: "ductus"
description: "Rule that triggers preprocessing action, when a research wp1 experiment has been submitted to the inbox"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/ngs/preprocessing/forskning/INBOX"

action:
    ref: "ductus.wp1_preprocess_inbox"
    parameters:
        runfolder: "{{trigger.runfolder}}"
        runfolder_host: "{{trigger.host}}"
        project_type: "forskning"
