---
name: "wp1_clinic_fetch_outbox"
pack: "ductus"
description: "Rule that triggers a fetching action, when a clincal wp1 experiment has been submitted to the outbox"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/nobackup/ngs/klinik/OUTBOX"

action:
    ref: "ductus.wp1_fetch_outbox"
    parameters:
        runfolder: "{{trigger.runfolder}}"
        project_type: "klinik"
