---
name: "wp2_twist_tm_processing_inbox"
pack: "ductus"
description: "..."
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "Twist_Myeloid/Workarea"

action:
    ref: "ductus.process_wp2_twist_tm_inbox_data"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
