---
name: "wp3_processing_inbox_TWIST"
pack: "ductus"
description: "TWIST rule running on facility cluster"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
        type: "contains"
        pattern: "/projects/wp3/nobackup/TWIST/INBOX/"

action:
    ref: "ductus.wp3_process_inbox"
    parameters:
        host: "{{trigger.host}}"
        SS_folder: "{{trigger.runfolder}}"
        runpanel: "TWIST"
        bcbio_version: "1.1.5"
